---
apiVersion: v2
name: keycloak-auth
description: >
  A helm chart to manage Keycloak deployment and auth provider configuration on OpenShift
type: application
version: 0.1.0
appVersion: 0.1.0

dependencies:
  - name: cloudnative-pg
    version: 0.1.0
    repository: file://../cloudnative-pg
    condition: cloudnative-pg.enabled
