{{- if .Values.pullSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-pull-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ toJson .Values.pullSecret | b64enc }}
{{- end }}
