---
baseName: worker-h100
desiredReplicas: 0
instanceType: p5.4xlarge
nodeLabels:
  gpu-class: large
  jharmison.dev/gpu-type: h100
  node-role.kubernetes.io/gpu: ''
taints:
- effect: NoSchedule
  key: nvidia.com/gpu
  value: h100
