providers:
  htpasswd: null
  github:
    organizations:
      - rhai-code

admins:
  - jharmison-redhat
  - aliciavcao
  - cedricclyburn
  - cnuland
  - deewhyweb
  - FrankLaVigne
  - gshipley
  - lkerriso
  - RobbieJ
  - taylorjordanNC
  - soyr-redhat
