{{- range $operator, $config := .Values.operators }}
{{- if eq ($config.installPlanApproval | default "Automatic") "Manual" }}
{{- if not $config.startingCSV }}
{{- fail "Manual approvals with this chart require pinning a specific CSV with startingCSV for the operator" }}
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: approve-{{ $operator }}
  namespace: {{ $config.namespace | default "openshift-operators" }}
  labels:
    {{- include "install-operators.labels" $ | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: approve-{{ $operator }}
  labels:
    {{- include "install-operators.labels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: approve-{{ $operator }}
  namespace: {{ $config.namespace | default "openshift-operators" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: approve-{{ $operator }}-script
  namespace: {{ $config.namespace | default "openshift-operators" }}
  labels:
    {{- include "install-operators.labels" $ | nindent 4 }}
data:
  approve-operator.sh: |
    {{- tpl ($.Files.Get "files/approve-operator.sh") (list $operator $config) | nindent 4 }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: approve-{{ $operator }}
  namespace: {{ $config.namespace | default "openshift-operators" }}
  labels:
    {{- include "install-operators.labels" $ | nindent 4 }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  backoffLimit: 4
  template:
    spec:
      serviceAccountName: approve-{{ $operator }}
      restartPolicy: Never
      containers:
      - name: approve-operator
        image: {{ $.Values.global.toolsImage }}
        imagePullPolicy: IfNotPresent
        command: ["/mnt/approve-operator.sh"]
        env:
          - name: PACKAGE
            value: {{ $operator }}
          - name: PACKAGE_NAMESPACE
            value: {{ $config.namespace | default "openshift-operators" }}
          - name: CSV
            value: {{ $config.startingCSV }}
        volumeMounts:
          - name: approve-operator-script
            mountPath: /mnt
      volumes:
        - name: approve-operator-script
          configMap:
            name: approve-{{ $operator }}-script
            defaultMode: 493
{{- end }}
{{- end }}
