apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cloudnative-pg
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  channel: {{ .Values.channel }}
  installPlanApproval: Automatic
  name: cloudnative-pg
  source: certified-operators
  sourceNamespace: openshift-marketplace
