---
channel: fast-3.x

dataScienceCluster:
  components:
    dashboard:
      managementState: Managed
    feastoperator:
      managementState: Managed
    kserve:
      nim:
        managementState: Removed
      rawDeploymentServiceConfig: Headless
      managementState: Managed
    kueue:
      defaultClusterQueueName: default
      defaultLocalQueueName: default
      managementState: Removed
    llamastackoperator:
      managementState: Managed
    modelregistry:
      registriesNamespace: rhoai-model-registries
      managementState: Managed
    ray:
      managementState: Managed
    trainingoperator:
      managementState: Managed
    trustyai:
      eval:
        lmeval:
          permitCodeExecution: deny
          permitOnline: deny
      managementState: Managed
    workbenches:
      workbenchNamespace: rhods-notebooks
      managementState: Managed

dataScienceClusterInitialization: null
dashboardConfig:
  disableLMEval: false
  genAiStudio: true
  modelAsService: true

modelServerSizes: null
notebookSizes: null
